#!/bin/bash

##########################################################################
#  update-gazebo-rcll - update Gazebo RCLL repo
#
#  Created: Mon May 30 21:58:52 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Assumes $SIMSTICK_UPDATE_PATH to be set by simstick-update (stage 0)


# check if user has non-password access rights

# simply rebuild libs/tf
make -C $FAWKES_DIR/fawkes/src/libs/tf/
make -C $FAWKES_DIR/fawkes/src/plugins/clips-executive/

